version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Node.js version:"
      - node --version
      - echo "NPM version:"
      - npm --version
      - echo "Current directory contents:"
      - ls -la
      - echo "Building the React app..."
      - npm run build
      - echo "Build completed successfully"
      - echo "Checking build directory:"
      - ls -la build/

  post_build:
    commands:
      - echo Build completed successfully
      - echo "Checking if build directory exists..."
      - if [ -d "build" ]; then
          echo "build directory found, listing contents:";
          ls -la build/;
          echo "Uploading to S3...";
          aws s3 sync build/ s3://kobras --delete;
        else
          echo "build directory not found - build may have failed";
          exit 1;
        fi

artifacts:
  files:
    - "**/*"
  base-directory: build
  discard-paths: no
  name: react-app-build

cache:
  paths:
    - node_modules/**/*
