version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  pre_build:
    commands:
      - echo Logging build information...
      - node --version
      - npm --version
      - echo Build started on `date`

  build:
    commands:
      - echo Building the React app...
      - npm run build
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Build completed successfully
      - ls -la dist/

artifacts:
  files:
    - "**/*"
  base-directory: dist
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
