version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Node.js version:"
      - node --version
      - echo "NPM version:"
      - npm --version
      - echo "Current directory contents:"
      - ls -la
      - echo "Building the React app..."
      - npm run build
      - echo "Build completed successfully"
      - echo "Checking dist directory:"
      - ls -la dist/

  post_build:
    commands:
      - echo Build completed successfully
      - echo "Checking if dist directory exists..."
      - if [ -d "dist" ]; then
        echo "dist directory found, listing contents:";
        ls -la dist/;
        echo "Uploading to S3...";
        aws s3 sync dist/ s3://lolita-go --delete;
        else
        echo "dist directory not found - build may have failed";
        exit 1;
        fi

artifacts:
  files:
    - "**/*"
  base-directory: dist
  discard-paths: no
  name: react-app-build

cache:
  paths:
    - node_modules/**/*
